FROM nginx
COPY content /usr/share/nginx/html

# RUN rm /etc/nginx/conf.d/default.conf
#COPY . /usr/share/nginx/html
# COPY conf /etc/nginx

# RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY conf /etc/nginx/conf.d
